services:
  cpython:
    build: 
      context: .
      dockerfile: Dockerfile.cpython
    volumes:
      - .:/app
      - ./results/cpython:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1

  pypy:
    build: 
      context: .
      dockerfile: Dockerfile.pypy
    volumes:
      - .:/app
      - ./results/pypy:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
