services:
  cpython:
    build: 
      context: .
      dockerfile: Dockerfile.cpython
    volumes:
      - .:/app
      - ./results/cpython:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["cpython"]  # Default command, can be overridden

  pypy:
    build: 
      context: .
      dockerfile: Dockerfile.pypy
    volumes:
      - .:/app
      - ./results/pypy:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["pypy"]  # Default command, can be overridden
