services:
  benchmarks:
    build: 
      context: .
      dockerfile: Dockerfile.cpython
    volumes:
      - .:/app
      - ./results:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["cpython"]  # Default to CPython tests

  cython:
    build: 
      context: .
      dockerfile: Dockerfile.cpython
    volumes:
      - .:/app
      - ./results:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["cython"]  # Cython tests

  pypy:
    build: 
      context: .
      dockerfile: Dockerfile.pypy
    volumes:
      - .:/app
      - ./results:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["pypy"]  # PyPy tests
    depends_on:
      - benchmarks
