services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    image: py-perf-compare-base

  cpython:
    build:
      context: .
      dockerfile: docker/Dockerfile.cpython
    volumes:
      - ./results:/results
    depends_on:
      - base
    command: ["cpython", "--runs", "3", "--prime-upper-bound", "10000", "--matrix-dimension", "200", "--fibonacci-length", "30"]

  pypy:
    build:
      context: .
      dockerfile: docker/Dockerfile.pypy
    volumes:
      - ./results:/results
    depends_on:
      cpython:
        condition: service_completed_successfully
    command: ["pypy", "--runs", "3", "--prime-upper-bound", "10000", "--matrix-dimension", "200", "--fibonacci-length", "30"]

  benchmark-controller:
    build:
      context: .
      dockerfile: docker/Dockerfile.cpython
    volumes:
      - ./results:/results
    depends_on:
      pypy:
        condition: service_completed_successfully
    command: ["all", "--runs", "3", "--prime-upper-bound", "10000", "--matrix-dimension", "200", "--fibonacci-length", "30"]
