services:
  benchmark-controller:  # neutral controller that orchestrates benchmarks
    build: 
      context: .
      dockerfile: Dockerfile.cpython
    volumes:
      - .:/app
      - ./results:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]

  cpython:  # specific CPython runtime
    build: 
      context: .
      dockerfile: Dockerfile.cpython
    volumes:
      - .:/app
      - ./results:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["cpython"]
    depends_on:
      - benchmark-controller

  cython:  # specific Cython runtime
    build: 
      context: .
      dockerfile: Dockerfile.cpython
    volumes:
      - .:/app
      - ./results:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["cython"]
    depends_on:
      - benchmark-controller

  pypy:  # specific PyPy runtime
    build: 
      context: .
      dockerfile: Dockerfile.pypy
    volumes:
      - .:/app
      - ./results:/results
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
    command: ["pypy"]
    depends_on:
      - benchmark-controller
