services:
  benchmarks:
    build: .
    volumes:
      - .:/app
      - ./results:/results
      # Don't sync virtual environments back to host
      - /app/venv
      - /app/__pycache__
      - /app/**/__pycache__
    environment:
      - PYTHONPATH=/app
      # Disable Python bytecode generation for faster startup
      - PYTHONDONTWRITEBYTECODE=1
